[build]
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  # এটি সরাসরি true না লিখে নিচের মতো খালি রাখলে বা বাদ দিলেও চলবে
  # Netlify এখন অটোমেটিক ES Modules বা CommonJS হ্যান্ডেল করে।
  external_node_modules = []
